const express = require("express");
const router = express.Router();
const authController = require("../controllers/auth.controller");
const { verifyToken } = require("../middlewares/verifyToken");
router.post("/register", authController.regitation);
router.get("/verify/:token", authController.verifyToken);
router.post("/login", authController.login);
router.get("/logout", authController.logout);
router.post("/forgot", authController.forgotPassword);
router.post("/otp", authController.giveOTP);
router.post("/reset", authController.resetPassword);
router.post("/change-password", verifyToken, authController.changePassword);
router.get("/check-auth", authController.checkAuth);
module.exports = router;
